ROLLNAME 	= kernel
RELEASE		= 0
COLOR		= firebrick

REDHAT.ROOT	= $(PWD)
BOOTABLE	= 1

#KICKSTART_LANG		= "ko_KR"
#KICKSTART_LANGSUPPORT	= "ko_KR.UTF-8 ko_KR ko en_US.UTF-8 en_US"

KICKSTART_LANG		= "en_US"
KICKSTART_LANGSUPPORT	= "en_US"

